### ISSUE TITLE
UnscaffoldedContigError: Contigs are not included in scaffolding output with when generating new SCAFFOLD after modifying in Juicebox 1.11.08

### ISSUE THREAD

**Issue by tiramisutes** [phasegenomics/juicebox_scripts#29]
Hi,
I  get some problems when running `juicebox_assembly_converter.py`  to generate a new scaffold.
```
python juicebox_assembly_converter.py -a genome.FINAL.review.no_gaps.assembly -f genome.fasta -p newgenome

Processing assembly file. Details:
Assembly:                       genome.FINAL.review.no_gaps.assembly
Fasta:                          genome.fasta
Output prefix:                  newgenome
Contig mode:                    False
Simple Chromosome Names:        False

Reading sequences from genome.fasta...
.
Sequences read

Reading .assembly file genome.FINAL.review.no_gaps.assembly...
Traceback (most recent call last):
  File "../../bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 885, in <module>
    processed_assembly = JuiceboxConverter().process(fasta, assembly,
  File "../../bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 87, in process
    assembly_map, scaffolds = self._read_assembly(assembly, contig_mode=contig_mode)
  File "../../bin/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 225, in _read_assembly
    raise UnscaffoldedContigError('Contigs are not included in scaffolding output: {0}'.format(unscaffolded_contigs))
__main__.UnscaffoldedContigError: Contigs are not included in scaffolding output: ['SuperScaffold29:::fragment_5:::overhang_2:::gap', 'SuperScaffold256:::fragment_6:::debris', 'SuperScaffold100530:::fragment_3:::debris:::overhang_2:::gap', 'SuperScaffold100530:::fragment_4:::gap', 'SuperScaffold100530:::fragment_5:::debris:::overhang_1:::gap', 'SuperScaffold100530:::fragment_6:::overhang_2:::gap', 'SuperScaffold47:::overhang_1:::gap', 'SuperScaffold47:::overhang_3:::gap']
```
In the genome.fasta have followed header:
```
>SuperScaffold1
>SuperScaffold3
>SuperScaffold4
>SuperScaffold5
>SuperScaffold7
>SuperScaffold8
>SuperScaffold9
>SuperScaffold10
>SuperScaffold12
>SuperScaffold13
>SuperScaffold14
>SuperScaffold16
```
The **genome.FINAL.review.no_gaps.assembly** was export from Juicebox 1.11.08 and has run `degap_assembly.py` to remove gap.
```
>SuperScaffold1:::fragment_1 1 19713205
>SuperScaffold1:::fragment_2:::debris 2 22000
>SuperScaffold1:::fragment_3 3 48000
>SuperScaffold1:::fragment_4:::debris 4 5000
>SuperScaffold1:::fragment_5 5 42125000
>SuperScaffold1:::fragment_6:::debris 6 50000
>SuperScaffold1:::fragment_7 7 26095
>SuperScaffold3:::fragment_1:::debris 8 4469
>SuperScaffold3:::fragment_2 9 57968179
>SuperScaffold4:::fragment_1:::debris 10 174876
>SuperScaffold4:::fragment_2 11 22148658
>SuperScaffold4:::fragment_3:::debris 12 200000
>SuperScaffold4:::fragment_4 13 28786399
```
Any help is much appreciated.
Thanks.

**Comment by Hannah1746** [comment]
How did you fix this? I am having the same problem?
